# Generated by Django 5.0.1 on 2024-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.FilePathField(blank=True),
        ),
    ]
