# Generated by Django 5.0.1 on 2024-07-05 18:47

import solar_player_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0003_artist_remove_track_image_alter_track_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FilePathField(blank=True, path=solar_player_api.models.artists_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.FilePathField(path=solar_player_api.models.tracks_path),
        ),
    ]
