# Generated by Django 5.0.1 on 2024-07-07 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0006_alter_artist_image_alter_playlist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlist_tracks', to='solar_player_api.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(related_name='track_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
