# Generated by Django 5.0.1 on 2024-07-07 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0007_alter_playlist_tracks_alter_track_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlist_tracks', to='solar_player_api.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='track_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
