# Generated by Django 5.0.1 on 2024-07-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0009_alter_customuser_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
