# Generated by Django 5.0.1 on 2024-07-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0010_alter_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_listened',
        ),
    ]
