# Generated by Django 5.0.1 on 2024-07-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0011_remove_customuser_last_listened'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
