# Generated by Django 5.0.1 on 2024-07-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0013_playlist_playlisttracks_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.CharField(max_length=1000),
        ),
    ]
