# Generated by Django 5.0.1 on 2024-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_player_api', '0014_alter_track_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='license',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
